#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated by tools/build-bootstrap.py. Edit the helper sources, not this file.
# HTTPS bootstrap trust is separate from independently trusted SSH artifact signing.
# No additional helper scripts are downloaded.
# Parse the complete function before doing work, including when piped into Bash.
declass_bootstrap_main() {
    set -euo pipefail
    umask 077
    for tool in bash cat chmod mktemp rm; do
        command -v "$tool" >/dev/null 2>&1 || { printf 'declass install: missing %s\n' "$tool" >&2; return 1; }
    done
    declass_bootstrap_scratch=$(mktemp -d "${TMPDIR:-/tmp}/declass-bootstrap.XXXXXXXX")
    trap 'rm -rf "$declass_bootstrap_scratch"' EXIT
    # tools/install-release.sh SHA256 55fe4ab8ac0f464275e7ee1e1637e4034cedc12d8a48f09b2984c0e56f535fa9
    cat >"$declass_bootstrap_scratch/install-release.sh" <<'DECLASS_EMBEDDED_55FE4AB8AC0F464275E7EE1E1637E4034CEDC12D8A48F09B2984C0E56F535FA9'
#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Install signed releases when a trusted signer is configured; otherwise
# checksum-verified preview assets, with a notice.
# Usage: tools/install-release.sh [VERSION | --version VERSION] [--signers FILE]
#        [--url HTTPS_ASSET_DIRECTORY] [--allow-unsigned] [--no-modify-path]
#        (default version: latest stable release)
# DECLASS_INSTALL_DIR defaults to ~/.local/bin; DECLASS_DATA_DIR to ~/.local/share/declass.
# Defaults to GitHub Releases (maximpri/duet, tag vVERSION). The corresponding
# source, licenses and signed release records are retained locally.
set -euo pipefail
umask 077

fail() { printf 'declass install-release: %s\n' "$*" >&2; exit 1; }
usage() {
    cat <<'HELP'
Usage: install.sh [VERSION | --version VERSION] [--signers FILE]
                  [--url HTTPS_ASSET_DIRECTORY] [--allow-unsigned]
                  [--no-modify-path]
Defaults to the latest stable maximpri/duet GitHub release for this OS/CPU.
Trust file: $DECLASS_CONFIG_HOME/allowed_signers, or ~/.config/declass/allowed_signers.
Obtain that file through an independently trusted channel before installing.
With a trust file (or --signers), a valid signature is required: no fallback.
Without one, checksum-only preview assets are installed; checksums do not
authenticate the publisher. --allow-unsigned selects them even with a trust file.
Installs in ~/.local/bin and retains matching source and notices under
~/.local/share/declass/releases. DECLASS_INSTALL_DIR / DECLASS_DATA_DIR override those paths.
When ~/.local/bin is not on PATH, one marked line adding it is appended to your
shell's startup file; --no-modify-path (or DECLASS_NO_MODIFY_PATH=1) leaves it alone.
No sudo or downloaded signing key.
HELP
}
version=""
url=""
allow_unsigned=false
signers_given=false
modify_path=true
[ "${DECLASS_NO_MODIFY_PATH:-}" != 1 ] || modify_path=false
signers="${DECLASS_CONFIG_HOME:-$HOME/.config/declass}/allowed_signers"
while [ $# -gt 0 ]; do
    case "$1" in
    -h | --help) usage; exit 0 ;;
    --allow-unsigned) allow_unsigned=true; shift ;;
    --no-modify-path) modify_path=false; shift ;;
    --url | --signers | --version)
        [ $# -ge 2 ] && [ -n "$2" ] || fail "$1 requires a value"
        case "$1" in
            --url) url="$2" ;;
            --signers) signers="$2"; signers_given=true ;;
            --version) [ -z "$version" ] || fail "specify one version"; version="$2" ;;
        esac
        shift 2
        ;;
    -*) fail "unknown option: $1" ;;
    *) [ -z "$version" ] || fail "specify one version"; version="$1"; shift ;;
    esac
done
[ -n "$version" ] || version=latest
if [ "$version" != latest ]; then
    [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$ ]] || fail "specify latest or a version as x.y.z[-pre]"
fi
# No trust file configured: nothing could authenticate a signature, so install
# the preview assets. A configured trust file always requires a signature.
if ! $allow_unsigned && ! $signers_given && [ ! -e "$signers" ]; then
    allow_unsigned=true
fi
if ! $allow_unsigned; then
    [ -f "$signers" ] && [ -r "$signers" ] && [ -s "$signers" ] || fail "no nonempty readable allowed-signers file at $signers; obtain the release signer through an independent trusted channel, or pass --signers FILE"
fi
for tool in curl uname mktemp cp chmod mv mkdir rm grep tar bash dirname; do
    command -v "$tool" >/dev/null 2>&1 || fail "required command not found: $tool"
done
if ! $allow_unsigned; then
    command -v ssh-keygen >/dev/null 2>&1 || fail "ssh-keygen is required for signed releases"
fi
command -v shasum >/dev/null 2>&1 || command -v sha256sum >/dev/null 2>&1 || fail "shasum or sha256sum is required"
verifier="$(cd "$(dirname "$0")" && pwd -P)/verify-release.sh"
[ -x "$verifier" ] || fail "verify-release.sh must be present beside this trusted installer"
checker="$(dirname "$verifier")/verify-checksums.sh"
[ -x "$checker" ] || fail "verify-checksums.sh must be present beside this trusted installer"
os=$(uname -s)
arch=$(uname -m)
# A translated shell on Apple Silicon should install the native ARM64 binary.
if [ "$os:$arch" = Darwin:x86_64 ] && command -v sysctl >/dev/null 2>&1; then
    translated=$(sysctl -in sysctl.proc_translated 2>/dev/null || true)
    [ "$translated" != 1 ] || arch=arm64
fi
case "$os:$arch" in
Darwin:arm64 | Darwin:aarch64) target=aarch64-apple-darwin ;;
Darwin:x86_64) target=x86_64-apple-darwin ;;
Linux:aarch64 | Linux:arm64) target=aarch64-unknown-linux-gnu ;;
Linux:x86_64 | Linux:amd64) target=x86_64-unknown-linux-gnu ;;
*) fail "supported platforms are macOS and GNU/Linux on ARM64 or x86-64" ;;
esac
install_dir="${DECLASS_INSTALL_DIR:-$HOME/.local/bin}"
data_dir="${DECLASS_DATA_DIR:-$HOME/.local/share/declass}"
for destination in "$install_dir" "$data_dir"; do
    case "$destination" in /*) ;; *) fail "DECLASS_INSTALL_DIR and DECLASS_DATA_DIR must be absolute paths" ;; esac
done
[ ! -d "$install_dir/declass" ] || fail "destination is a directory: $install_dir/declass"

if [ "$version" = latest ]; then
    # Resolve once; every asset then uses the same pinned version directory.
    # GitHub's latest endpoint excludes drafts and prereleases. No JSON parser,
    # API token or mutable latest/download URL is needed.
    resolved=$(curl --proto '=https' --proto-redir '=https' --tlsv1.2 --fail --silent --show-error \
        --location --max-redirs 5 --connect-timeout 20 --max-time 60 --head \
        --output /dev/null --write-out '%{url_effective}' \
        https://github.com/maximpri/duet/releases/latest) ||
        fail "cannot resolve the latest stable GitHub release; none may be published, or GitHub is unavailable"
    case "$resolved" in
        https://github.com/maximpri/duet/releases/tag/v*) version=${resolved#https://github.com/maximpri/duet/releases/tag/v} ;;
        *) fail "no supported stable GitHub release found; expected a vX.Y.Z release tag" ;;
    esac
    [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "latest release is not a supported stable vX.Y.Z tag"
fi
[ -n "$url" ] || url="https://github.com/maximpri/duet/releases/download/v$version"
[[ "$url" =~ ^https://[^/?#]+(/[^?#]*)?$ ]] || fail "--url must be an HTTPS release-directory URL without query or fragment"
url=${url%/}
if $allow_unsigned; then
    printf 'Installing UNSIGNED Declass %s for %s: checksums verify integrity, not publisher identity.\n' "$version" "$target"
else
    printf 'Installing signed Declass %s for %s\n' "$version" "$target"
fi

scratch=$(mktemp -d "${TMPDIR:-/tmp}/declass-install-release.XXXXXXXX")
staged_binary=""
retained=""
cleanup() {
    rm -rf "$scratch"
    [ -z "$staged_binary" ] || rm -f "$staged_binary"
    [ -z "$retained" ] || rm -rf "$retained"
}
trap cleanup EXIT
binary="declass-$version-$target"
stem="$binary"
$allow_unsigned && stem="$stem-unsigned"
archive="$stem.tar.gz"
manifest="$stem.SHA256SUMS"
download() {
    curl --proto '=https' --proto-redir '=https' --tlsv1.2 --fail --silent --show-error \
        --location --max-redirs 5 --connect-timeout 20 --max-time 600 \
        --output "$2" "$url/$1" || fail "download failed: $1"
}
verify_payload() {
    if $allow_unsigned; then
        # Never silently downgrade a signed asset or ignore a present bad signature.
        [ ! -e "$1/SHA256SUMS.sig" ] && [ ! -L "$1/SHA256SUMS.sig" ] || fail 'unsigned assets must not contain a signature'
        "$checker" "$1"
    else
        "$verifier" "$1" --signers "$signers"
    fi
}
# A signing key is supplied independently, never downloaded with the payload.
download "$manifest" "$scratch/SHA256SUMS"
$allow_unsigned || download "$manifest.sig" "$scratch/SHA256SUMS.sig"
download "$archive" "$scratch/$archive"
verify_payload "$scratch"
# Inspect the authenticated/checksummed archive before extracting anything. Both
# package-release.sh (name) and cicd.sh (./name) use flat regular payload files.
# Reject extras, duplicates, links and nested paths even in an unsigned preview.
names=("$binary" "declass-$version.cdx.json" BUILDINFO.txt LICENSE NOTICE LICENSES.md
    LICENSE.gitleaks NOTICE.gitleaks "declass-$version-source.tar.gz" SOURCE.txt SHA256SUMS)
$allow_unsigned || names+=(SHA256SUMS.sig)
listing="$scratch/entries"
details="$scratch/types"
tar -tzf "$scratch/$archive" >"$listing" || fail 'cannot list release archive'
tar -tvzf "$scratch/$archive" >"$details" || fail 'cannot inspect release archive'
seen=""
exec 3<"$details"
while IFS= read -r name; do
    IFS= read -r detail <&3 || fail 'inconsistent archive listing'
    flat=${name#./}
    if [ "$name" = . ] || [ "$name" = ./ ]; then
        case "$detail" in d*) continue ;; *) fail 'invalid archive root entry' ;; esac
    fi
    case "$detail" in -*) ;; *) fail "archive entry is not a regular file: $name" ;; esac
    allowed=false
    for expected in "${names[@]}"; do [ "$flat" != "$expected" ] || allowed=true; done
    $allowed || fail "unexpected release archive entry: $name"
    grep -qxF -- "$flat" <<<"$seen" && fail "duplicate release archive entry: $flat"
    seen="${seen}${seen:+$'\n'}$flat"
done <"$listing"
exec 3<&-
payload="$scratch/payload"
mkdir "$payload"
for name in "${names[@]}"; do
    grep -qxF -- "$name" <<<"$seen" || fail "release archive lacks expected file: $name"
    entry="$name"
    grep -qxF -- "$entry" "$listing" || entry="./$name"
    # stdout extraction never restores archive ownership, modes or paths.
    tar -xOf "$scratch/$archive" "$entry" >"$payload/$name" || fail "cannot extract expected file: $name"
done
verify_payload "$payload"
grep -qxF -- "declass $version" "$payload/BUILDINFO.txt" || fail "signed build metadata does not match version $version"
grep -qxF -- "target $target" "$payload/BUILDINFO.txt" || fail "signed build metadata does not match target $target"

mkdir -p "$install_dir"
staged_binary=$(mktemp "$install_dir/.declass.XXXXXXXX")
cp "$payload/$binary" "$staged_binary"
chmod 755 "$staged_binary"
# Required authentication (unless explicitly unsigned) and all hashes passed
# before any downloaded code runs.
reported_version=$("$staged_binary" --version) || fail "verified binary cannot run on this host; existing installation retained"
[ "$reported_version" = "declass $version" ] || fail "verified binary reports an unexpected version: $reported_version"
mkdir -p "$data_dir/releases"
retained=$(mktemp -d "$data_dir/releases/$version-$target.XXXXXXXX")
cp "$payload"/* "$retained/"
# Same-directory rename is atomic: download/verification/copy failures above
# never replace the existing executable. Existing release records are retained.
mv -f "$staged_binary" "$install_dir/declass"
staged_binary=""
installed_records="$retained"
retained=""
printf 'Installed %s at %s/declass\n' "$reported_version" "$install_dir"
if $allow_unsigned; then
    printf 'Checksum-verified source and records (unsigned): %s\n' "$installed_records"
else
    printf 'Verified source, licenses and release records: %s\n' "$installed_records"
fi
case ":$PATH:" in
    *":$install_dir:"*) printf '\nRun it in your project directory:  declass\n' ;;
    *)
        if ! $modify_path; then
            printf '\nAdd %s to PATH to run declass (no shell profile was changed).\n' "$install_dir"
        else
            case "${SHELL##*/}" in
                zsh) profile="${ZDOTDIR:-$HOME}/.zshrc" ;;
                bash) if [ "$os" = Darwin ]; then profile="$HOME/.bash_profile"; else profile="$HOME/.bashrc"; fi ;;
                fish) profile="${XDG_CONFIG_HOME:-$HOME/.config}/fish/conf.d/declass.fish" ;;
                *) profile="$HOME/.profile" ;;
            esac
            if [ "${SHELL##*/}" = fish ]; then
                line="fish_add_path -g '$install_dir' # added by the declass installer"
            else
                line="export PATH=\"$install_dir:\$PATH\" # added by the declass installer"
            fi
            if [ -f "$profile" ] && grep -qF -- "$line" "$profile"; then
                printf '\n%s already adds %s to PATH.\n' "$profile" "$install_dir"
            else
                mkdir -p "$(dirname "$profile")"
                printf '\n%s\n' "$line" >>"$profile"
                printf '\nAdded %s to PATH in %s (remove the line marked "declass installer" to undo).\n' "$install_dir" "$profile"
            fi
            printf 'Open a new terminal, then run it in your project directory:  declass\n'
        fi
        ;;
esac
DECLASS_EMBEDDED_55FE4AB8AC0F464275E7EE1E1637E4034CEDC12D8A48F09B2984C0E56F535FA9
    # tools/verify-release.sh SHA256 5501d4cd7a0321a1bd805d784833e24a4138df4b4ca550ceb7b9d09c193ee38b
    cat >"$declass_bootstrap_scratch/verify-release.sh" <<'DECLASS_EMBEDDED_5501D4CD7A0321A1BD805D784833E24A4138DF4B4CA550CEB7B9D09C193EE38B'
#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Verifies a release directory made by tools/release.sh: SHA256SUMS carries a
# valid SSH signature (namespace declass-release) by a key in the allowed-signers
# file, and every file in the directory is listed there and matches.
#
#   tools/verify-release.sh <release dir> [--signers FILE]
#
# The signers file defaults to allowed_signers next to the owner config
# ($DECLASS_CONFIG_HOME/allowed_signers, else ~/.config/declass/allowed_signers),
# the file `declass doctor` checks. Each line: <identity> namespaces="declass-release" <public key>.
# Offline; needs ssh-keygen and shasum (or sha256sum). Exit 0 only when all holds.
set -euo pipefail

die() {
    echo "verify: FAILED: $*" >&2
    exit 1
}

dir=""
signers="${DECLASS_CONFIG_HOME:-$HOME/.config/declass}/allowed_signers"
while [ $# -gt 0 ]; do
    case "$1" in
    -h | --help)
        sed -n '3,12p' "$0" | sed 's/^# \{0,1\}//'
        exit 0
        ;;
    --signers)
        [ $# -ge 2 ] || die "--signers needs a file"
        signers="$2"
        shift 2
        ;;
    -*) die "unknown option $1" ;;
    *)
        [ -z "$dir" ] || die "one release directory only"
        dir="$1"
        shift
        ;;
    esac
done
[ -n "$dir" ] || {
    echo "usage: tools/verify-release.sh <release dir> [--signers FILE]" >&2
    exit 2
}
[ -d "$dir" ] || die "$dir is not a directory"
[ -f "$signers" ] || die "no allowed-signers file at $signers (get the release signer line from a trusted channel)"
sums="$dir/SHA256SUMS"
sig="$dir/SHA256SUMS.sig"
[ -f "$sums" ] || die "$sums is missing"
[ -f "$sig" ] || die "$sig is missing: the release is unsigned"
command -v ssh-keygen >/dev/null || die "ssh-keygen is required"

# 1. The signature: which trusted identity made it, then a full verification.
principals=$(ssh-keygen -Y find-principals -s "$sig" -f "$signers" 2>/dev/null) ||
    die "SHA256SUMS is not signed by any key in $signers"
signer=""
while IFS= read -r p; do
    if ssh-keygen -Y verify -f "$signers" -I "$p" -n declass-release -s "$sig" <"$sums" >/dev/null 2>&1; then
        signer="$p"
        break
    fi
done <<<"$principals"
[ -n "$signer" ] || die "the signature over SHA256SUMS does not verify (namespace declass-release)"

# Shared strict manifest parser; signature validation above is mandatory.
checker="$(cd "$(dirname "$0")" && pwd -P)/verify-checksums.sh"
[ -x "$checker" ] || die 'verify-checksums.sh must be beside this verifier'
count=$("$checker" "$dir" --count) || die 'release checksum validation failed'

echo "verified: SHA256SUMS signed by $signer; $count file(s) match"
DECLASS_EMBEDDED_5501D4CD7A0321A1BD805D784833E24A4138DF4B4CA550CEB7B9D09C193EE38B
    # tools/verify-checksums.sh SHA256 bd4cdc5155678f9f2cee1b1422e603c87c60d8a3bd3efd5c1143ba9dbb0d8855
    cat >"$declass_bootstrap_scratch/verify-checksums.sh" <<'DECLASS_EMBEDDED_BD4CDC5155678F9F2CEE1B1422E603C87C60D8A3BD3EFD5C1143BA9DBB0D8855'
#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Verify strict flat SHA256SUMS coverage and file integrity; no publisher authentication.
# Usage: verify-checksums.sh DIRECTORY [--count]
set -euo pipefail

die() { printf 'checksums: FAILED: %s\n' "$*" >&2; exit 1; }
dir=""
count_only=false
while [ $# -gt 0 ]; do
    case "$1" in
        --count) count_only=true ;;
        -*) die "unknown option: $1" ;;
        *) [ -z "$dir" ] || die 'one release directory only'; dir=$1 ;;
    esac
    shift
done
[ -n "$dir" ] && [ -d "$dir" ] || die 'specify a release directory'
sums="$dir/SHA256SUMS"
[ -f "$sums" ] && [ ! -L "$sums" ] || die 'SHA256SUMS must be a regular file'
command -v shasum >/dev/null 2>&1 || command -v sha256sum >/dev/null 2>&1 || die 'shasum or sha256sum is required'

# 2. The checksums: every line must describe exactly one ordinary filename.
# Hash tools can warn about malformed lines and still exit successfully; those
# lines must never count as covering an otherwise unchecked release file.
# Check raw bytes first: some Bash versions discard NUL bytes during `read`.
if LC_ALL=C grep -aq '[[:cntrl:]]' "$sums"; then
    die "SHA256SUMS contains a control character"
fi
sum_record='^[0-9a-fA-F]{64} [ *](.+)$'
listed=""
count=0
while IFS= read -r line || [ -n "$line" ]; do
    [[ "$line" =~ $sum_record ]] || die "SHA256SUMS contains a malformed checksum record"
    name="${BASH_REMATCH[1]}"
    case "$name" in
    "" | */* | .* | *\\*) die "SHA256SUMS lists an unexpected name: $name" ;;
    esac
    if grep -qxF -- "$name" <<<"$listed"; then
        die "SHA256SUMS lists a duplicate filename: $name"
    fi
    listed="${listed}${listed:+$'\n'}$name"
    count=$((count + 1))
done <"$sums"
[ "$count" -gt 0 ] || die "SHA256SUMS contains no files"
for f in "$dir"/* "$dir"/.[!.]* "$dir"/..?*; do
    [ -e "$f" ] || [ -L "$f" ] || continue
    [ -f "$f" ] && [ ! -L "$f" ] || die "$f is not a regular release file"
    name=$(basename "$f")
    case "$name" in SHA256SUMS | SHA256SUMS.sig) continue ;; esac
    grep -qxF -- "$name" <<<"$listed" || die "$name is in the release directory but not in SHA256SUMS"
done
if command -v shasum >/dev/null; then
    check() { shasum -a 256 -c --quiet "$@"; }
else
    check() { sha256sum -c --quiet "$@"; }
fi
(cd "$dir" && check SHA256SUMS) || die "a file does not match SHA256SUMS"

if $count_only; then
    printf '%s\n' "$count"
else
    printf 'verified: %s file(s) match SHA256SUMS (integrity only; publisher not authenticated)\n' "$count"
fi
DECLASS_EMBEDDED_BD4CDC5155678F9F2CEE1B1422E603C87C60D8A3BD3EFD5C1143BA9DBB0D8855
    chmod 700 "$declass_bootstrap_scratch/install-release.sh" "$declass_bootstrap_scratch/verify-release.sh" "$declass_bootstrap_scratch/verify-checksums.sh"
    bash "$declass_bootstrap_scratch/install-release.sh" "$@" </dev/null
}
declass_bootstrap_main "$@"
