[package]
name = "duet-cli"
description = "Duet command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]

[[bin]]
name = "duet"
path = "src/main.rs"
