#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the standalone Bash installer; --check refuses source drift.

The bootstrap embeds all trusted helper sources, rather than downloading and
executing a mutable verifier. Python is needed only to regenerate this file.
End users need Bash and the release installer's ordinary platform tools.
"""

import argparse
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    parts = [
        "#!/usr/bin/env bash\n",
        "# SPDX-License-Identifier: GPL-3.0-or-later\n",
        "# Generated by tools/build-bootstrap.py. Edit the helper sources, not this file.\n",
        "# HTTPS bootstrap trust is separate from independently trusted SSH artifact signing.\n",
        "# No additional helper scripts are downloaded.\n",
        "# Parse the complete function before doing work, including when piped into Bash.\n",
        "declass_bootstrap_main() {\n",
        "    set -euo pipefail\n",
        "    umask 077\n",
        "    for tool in bash cat chmod mktemp rm; do\n",
        "        command -v \"$tool\" >/dev/null 2>&1 || { printf 'declass install: missing %s\\n' \"$tool\" >&2; return 1; }\n",
        "    done\n",
        "    declass_bootstrap_scratch=$(mktemp -d \"${TMPDIR:-/tmp}/declass-bootstrap.XXXXXXXX\")\n",
        "    trap 'rm -rf \"$declass_bootstrap_scratch\"' EXIT\n",
    ]
    for name in ("install-release.sh", "verify-release.sh", "verify-checksums.sh"):
        raw = (ROOT / "tools" / name).read_bytes()
        text = raw.decode("utf-8")
        assert text.endswith("\n")
        digest = hashlib.sha256(raw).hexdigest()
        delimiter = "DECLASS_EMBEDDED_" + digest.upper()
        assert delimiter not in text.splitlines()
        parts += [
            f"    # tools/{name} SHA256 {digest}\n",
            f"    cat >\"$declass_bootstrap_scratch/{name}\" <<'{delimiter}'\n",
            text,
            f"{delimiter}\n",
        ]
    parts += [
        "    chmod 700 \"$declass_bootstrap_scratch/install-release.sh\" \"$declass_bootstrap_scratch/verify-release.sh\" \"$declass_bootstrap_scratch/verify-checksums.sh\"\n",
        "    bash \"$declass_bootstrap_scratch/install-release.sh\" \"$@\" </dev/null\n",
        "}\n",
        "declass_bootstrap_main \"$@\"\n",
    ]
    return "".join(parts).encode("utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    target = ROOT / "install.sh"
    if args.check:
        if not target.is_file() or target.read_bytes() != expected:
            raise SystemExit("install.sh is stale; run python3 tools/build-bootstrap.py")
        print("Standalone installer matches all trusted helper sources.")
    else:
        target.write_bytes(expected)
        target.chmod(0o755)


if __name__ == "__main__":
    main()
